version: "3.9"

services:
  web:
    container_name: go_playground_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=offers_db

volumes:
  pg_data:
    driver: local